version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# 定义所有构建作业为一个列表
jobs:
  - name: "Build Documentation Portal"
    sphinx:
      configuration: docs-portal/conf.py
      builder: html
      fail_on_warning: false

  - name: "Build Product A Documentation"
    environment:
      multiproject: product_a
    sphinx:
      configuration: docs/conf.py
      builder: html

  - name: "Build Product B Documentation"
    environment:
      multiproject: product_b
    sphinx:
      configuration: docs/conf.py
      builder: html

# 所有作业共享的 Python 依赖安装
python:
  install:
    - requirements: requirements.txt