version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# 全局安装依赖
python:
  install:
    - requirements: requirements.txt

# 定义三个独立的构建作业
jobs:
  build_portal:
    name: "Build Documentation Portal"
    sphinx:
      configuration: docs-portal/conf.py
      builder: html
      # 门户构建输出到独立目录
      fail_on_warning: false

  build_product_a:
    name: "Build Product A Documentation"
    environment:
      # 关键：此变量将被 docs/conf.py 读取
      multiproject: product_a
    sphinx:
      configuration: docs/conf.py  # 使用同一个主配置
      builder: html

  build_product_b:
    name: "Build Product B Documentation"
    environment:
      multiproject: product_b
    sphinx:
      configuration: docs/conf.py
      builder: html