version: 2

# 1. 定义构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # 2. 在这里定义所有并行构建作业
  jobs:
    - name: "Build Documentation Portal"
      sphinx:
        configuration: docs-portal/conf.py
        builder: html
        fail_on_warning: false

    - name: "Build Product A Documentation"
      environment:
        multiproject: product_a
      sphinx:
        configuration: docs/conf.py
        builder: html

    - name: "Build Product B Documentation"
      environment:
        multiproject: product_b
      sphinx:
        configuration: docs/conf.py
        builder: html

# 3. 定义所有作业共享的依赖安装
python:
  install:
    - requirements: requirements.txt